### ISSUE TITLE
Not Found this Code

### ISSUE THREAD

**Issue by ghoshzsh** [arshbhatia8/CCC-Phase-4-exit-test#3]
![image](https://user-images.githubusercontent.com/73014371/229284488-ba7494cd-4894-4764-95e0-a782ecba3f11.png)

**Comment by ghoshzsh** [comment]
@arshbhatia8

**Comment by ghoshzsh** [comment]
https://www.onlinegdb.com/qkAcDfo9R

Add this code
@arshbhatia8

**Comment by arshbhatia8** [comment]
Sure
